language: java
jdk:
  - openjdk7
addons:
  postgresql: "9.4"
sudo: true
services:
  - postgresql
install:
  - mvn install -DskipTests -DskipWildfly -DskipDelombok -Dmaven.javadoc.skip=true -B -V
before_script:
  - sudo apt-get install postgresql-9.4-postgis-2.3 postgis-2.3 -y -q
  - psql -c "create user chouette with login createdb superuser encrypted  password 'chouette';" -U postgres
  - psql -c 'create database chouette_test with owner = chouette;' -U postgres
