package mobi.chouette.exchange.importer.updater;


/***
 * Class that stores all errorCodes generated by stop place repository (tiamat)
 *  (MUST MATCH WITH ERROR CODES DEFINED IN TIAMAT IN TiamatBusinessException class)
 */
public enum TiamatErrorsEnum {

    UNKNOWN(0),
    DUPLICATE_IMPORTED_ID(1),
    TRANSPORT_MODE_MISMATCH(2);

    private final int errorCode;

    TiamatErrorsEnum(int errorCode) {
        this.errorCode = errorCode;
    }

    public static TiamatErrorsEnum fromErrorCode(int errorCode) {
        for (TiamatErrorsEnum c : TiamatErrorsEnum.values()) {
            if (c.errorCode == errorCode) {
                return c;
            }
        }
        throw new IllegalArgumentException("unknown Tiamat error code:" + errorCode);
    }

    public int getErrorCode() {
        return errorCode;
    }


}
