package mobi.chouette.exchange.netexprofile.exporter;


import mobi.chouette.common.Context;
import mobi.chouette.exchange.netexprofile.Constant;
import mobi.chouette.exchange.netexprofile.JobDataTest;
import mobi.chouette.exchange.netexprofile.jaxb.NetexXMLProcessingHelperFactory;
import mobi.chouette.exchange.report.ActionReport;
import mobi.chouette.model.*;
import mobi.chouette.model.type.PTDirectionEnum;
import org.testng.Assert;
import org.testng.annotations.Test;

import javax.xml.bind.JAXBException;
import java.io.File;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.LocalTime;
import java.util.Arrays;
import java.util.Collections;
import java.util.HashSet;
import java.util.List;

import static mobi.chouette.common.Constant.*;
import static mobi.chouette.exchange.netexprofile.Constant.EXPORTABLE_NETEX_DATA;
import static mobi.chouette.exchange.netexprofile.Constant.MARSHALLER;

public class NetexSNCFMissingQuayTest {

	private Context createContext(boolean generateQuaysParameter, boolean quay1IsAuto, boolean quay2IsAuto, boolean quay3IsAuto) throws JAXBException {
        File file = new File("src/test/data/idfm/output/offre_TestCodifligne_.xml");
        file.getParentFile().mkdirs();

        // Company & Network
        Company company = new Company();
        company.setCode("myComp");
        company.setEmail("email@okinatest.com");
        company.setFareUrl("www.okinatest.com");
        company.setName("Okina test");
        company.setObjectId("Test:Company:1");

        Network network = new Network();
        network.setCompany(company);
        network.setObjectId("Test:Network:1");

        // Line
        Line line = new Line();
        line.setObjectId("TEST:Line:l1");
        line.setRegistrationNumber("l1");
        line.setCodifligne("TestCodifligne");
        line.setNetwork(network);
        line.setFlexibleService(true);

        // Route
        Route route = new Route();
        route.setObjectId("TEST:Route:r1");
        route.setName("Test Route");
        route.setLine(line);
        route.setDirection(PTDirectionEnum.A);

        // DestinationDisplay
        DestinationDisplay destinationDisplay = new DestinationDisplay();
        destinationDisplay.setObjectId("TEST:DestinationDisplay:dd1");
        destinationDisplay.setFrontText("Test Destination Display");

        // StopAreas
        StopArea stopArea1 = new StopArea();
        stopArea1.setObjectId("TEST:Quay:quay1");
        stopArea1.setQuayAutoGenerated(quay1IsAuto);

        StopArea stopArea2 = new StopArea();
        stopArea2.setObjectId("TEST:Quay:quay2");
        stopArea2.setQuayAutoGenerated(quay2IsAuto);

        StopArea stopArea3 = new StopArea();
        stopArea3.setObjectId("TEST:Quay:quay3");
        stopArea3.setQuayAutoGenerated(quay3IsAuto);

        // ScheduledStopPoints
        ScheduledStopPoint ssp1 = new ScheduledStopPoint();
        ssp1.setObjectId("TEST:ScheduledStopPoint:ssp1");
        ssp1.setContainedInStopAreaRef(new SimpleObjectReference(stopArea1));

        ScheduledStopPoint ssp2 = new ScheduledStopPoint();
        ssp2.setObjectId("TEST:ScheduledStopPoint:ssp2");
        ssp2.setContainedInStopAreaRef(new SimpleObjectReference(stopArea2));

        ScheduledStopPoint ssp3 = new ScheduledStopPoint();
        ssp3.setObjectId("TEST:ScheduledStopPoint:ssp3");
        ssp3.setContainedInStopAreaRef(new SimpleObjectReference(stopArea3));

        // StopPoints
        StopPoint sp1 = new StopPoint();
        sp1.setObjectId("TEST:StopPoint:sp1");
        sp1.setPosition(0);
        sp1.setScheduledStopPoint(ssp1);
        sp1.setRoute(route);

        StopPoint sp2 = new StopPoint();
        sp2.setObjectId("TEST:StopPoint:sp2");
        sp2.setPosition(1);
        sp2.setScheduledStopPoint(ssp2);
        sp2.setRoute(route);

        StopPoint sp3 = new StopPoint();
        sp3.setObjectId("TEST:StopPoint:sp3");
        sp3.setPosition(2);
        sp3.setScheduledStopPoint(ssp3);
        sp3.setDestinationDisplay(destinationDisplay);
        sp3.setRoute(route);

        List<StopPoint> stopPoints = Arrays.asList(sp1, sp2, sp3);
        route.setStopPoints(stopPoints);

        // JourneyPattern
        JourneyPattern journeyPattern = new JourneyPattern();
        journeyPattern.setObjectId("TEST:JourneyPattern:jp1");
        journeyPattern.setName("Test Journey Pattern");
        journeyPattern.setRoute(route);
        journeyPattern.setStopPoints(stopPoints);

        // Timetable
        Timetable timetable = new Timetable();
        timetable.setObjectId("TEST:Timetable:t1");
        Period period = new Period();
        period.setStartDate(LocalDate.of(2020, 1, 1));
        period.setEndDate(LocalDate.of(2020,12,31));
        timetable.setPeriods(Collections.singletonList(period));

        // VehicleJourneyAtStop
        VehicleJourneyAtStop vjas1 = new VehicleJourneyAtStop();
        vjas1.setObjectId("TEST:TimetablePassingTime:tpt1");
        vjas1.setDepartureTime(LocalTime.of(7, 0, 0));
        vjas1.setArrivalTime(LocalTime.of(7, 0, 0));
        vjas1.setStopPoint(sp1);

        VehicleJourneyAtStop vjas2 = new VehicleJourneyAtStop();
        vjas2.setObjectId("TEST:TimetablePassingTime:tpt2");
        vjas2.setDepartureTime(LocalTime.of(7, 15, 0));
        vjas2.setArrivalTime(LocalTime.of(7, 15, 0));
        vjas2.setStopPoint(sp2);

        VehicleJourneyAtStop vjas3 = new VehicleJourneyAtStop();
        vjas3.setObjectId("TEST:TimetablePassingTime:tpt3");
        vjas3.setDepartureTime(LocalTime.of(7, 30, 0));
        vjas3.setArrivalTime(LocalTime.of(7, 30, 0));
        vjas3.setStopPoint(sp3);

        List<VehicleJourneyAtStop> vjasList = Arrays.asList(vjas1, vjas2, vjas3);

        // Train
        Train train = new Train();
        train.setObjectId("FR:TrainNumber:1");
        train.setVersion("any");
        train.setDescription("Bordeaux - Marseille");
        train.setPublishedName("357224");

        // VehicleJourney
        VehicleJourney vehicleJourney = new VehicleJourney();
        vehicleJourney.setObjectId("TEST:VehicleJourney:vj1");
        vehicleJourney.setPublishedJourneyName("Test vehicle journey name");
        vehicleJourney.setJourneyPattern(journeyPattern);
        vehicleJourney.setVehicleJourneyAtStops(vjasList);
        vehicleJourney.setTimetables(Collections.singletonList(timetable));
        vehicleJourney.setRoute(route);
        vehicleJourney.setTrains(Collections.singletonList(train));

        // Footnote
        Footnote footnote = new Footnote();
        footnote.setObjectId("TEST:Footnote:f1");
        footnote.setLabel("Test Label");
        footnote.setCode("Test Code");
        vehicleJourney.setFootnotes(Collections.singletonList(footnote));

        // ExportableData
        ExportableData exportableData = new ExportableData();
        exportableData.setLine(line);
        exportableData.setRoutes(Collections.singletonList(route));
        exportableData.setJourneyPatterns(Collections.singletonList(journeyPattern));
        exportableData.setVehicleJourneys(Collections.singletonList(vehicleJourney));
        exportableData.setStopAreas(new HashSet<>(Arrays.asList(stopArea1, stopArea2, stopArea3)));
        exportableData.setTimetables(new HashSet<>(Collections.singletonList(timetable)));

        // Context
        Context context = new Context();
        JobDataTest jobData = new JobDataTest();
        jobData.setPathName("src/test/data/idfm");

        NetexprofileExportParameters parameters = new NetexprofileExportParameters();
        parameters.setExportStops(false);
        parameters.setAddMetadata(false);
        parameters.setDefaultCodespacePrefix("TEST");
        parameters.setExportGeneratedMissingQuays(generateQuaysParameter);

        context.put(Constant.CONFIGURATION, parameters);
        context.put(EXPORTABLE_DATA, exportableData);
        context.put(EXPORTABLE_NETEX_DATA, new ExportableNetexData());
        context.put(JOB_DATA, jobData);
        context.put(REPORT, new ActionReport());
        context.put(MARSHALLER, new NetexXMLProcessingHelperFactory().createFragmentMarshaller());

        return context;
    }

	@Test
    public void shouldExportStopPlaceRefsOnly_WhenNoQuaysGenerated_SNCFFile() throws Exception {
        Context context = createContext(false, false, false, false); // aucun quay généré
        context.put(CREATION_DATE, LocalDateTime.now());
        new NetexLineDataFranceProducer().produce(context);
        ExportableNetexData result = (ExportableNetexData) context.get(EXPORTABLE_NETEX_DATA);

        // Tous les QuayRef doivent être présents
        result.getStopAssignments().values().forEach(sa -> Assert.assertNotNull(sa.getQuayRef()));
    }

    @Test
    public void shouldExportGeneratedQuayRefs_WhenQuaysAutoGenerated_SNCFFile() throws Exception {
        Context context = createContext(true, true, true, true); // tous les quays générés
        context.put(CREATION_DATE, LocalDateTime.now());
        new NetexLineDataFranceProducer().produce(context);
        ExportableNetexData result = (ExportableNetexData) context.get(EXPORTABLE_NETEX_DATA);

        // Tous les QuayRef doivent être présents
        Assert.assertEquals(result.getStopAssignments().get("TEST:PassengerStopAssignment:ssp1:LOC").getQuayRef().getValue().getRef(), "TEST:Quay:quay1");
        Assert.assertEquals(result.getStopAssignments().get("TEST:PassengerStopAssignment:ssp2:LOC").getQuayRef().getValue().getRef(), "TEST:Quay:quay2");
        Assert.assertEquals(result.getStopAssignments().get("TEST:PassengerStopAssignment:ssp3:LOC").getQuayRef().getValue().getRef(), "TEST:Quay:quay3");
    }

    @Test
    public void shouldExportImportedQuayRefs_WhenUsingStandardNetexFile() throws Exception {
        Context context = createContext(true, false, false, false); // quays importés
        context.put(CREATION_DATE, LocalDateTime.now());
        new NetexLineDataFranceProducer().produce(context);
        ExportableNetexData result = (ExportableNetexData) context.get(EXPORTABLE_NETEX_DATA);

        // Tous les QuayRef doivent être présents (importés)
        Assert.assertEquals(result.getStopAssignments().get("TEST:PassengerStopAssignment:ssp1:LOC").getQuayRef().getValue().getRef(), "TEST:Quay:quay1");
        Assert.assertEquals(result.getStopAssignments().get("TEST:PassengerStopAssignment:ssp2:LOC").getQuayRef().getValue().getRef(), "TEST:Quay:quay2");
        Assert.assertEquals(result.getStopAssignments().get("TEST:PassengerStopAssignment:ssp3:LOC").getQuayRef().getValue().getRef(), "TEST:Quay:quay3");
    }

    @Test
    public void shouldExportOnlyImportedQuayRefs_WhenComplementaryFileUsed_WithoutGeneration() throws Exception {
        Context context = createContext(false, true, false, true); // mix : quay2 importé, les autres non générés
        context.put(CREATION_DATE, LocalDateTime.now());
        new NetexLineDataFranceProducer().produce(context);
        ExportableNetexData result = (ExportableNetexData) context.get(EXPORTABLE_NETEX_DATA);

        // Seul quay2 doit être présent
        Assert.assertNull(result.getStopAssignments().get("TEST:PassengerStopAssignment:ssp1:LOC").getQuayRef());
        Assert.assertEquals(result.getStopAssignments().get("TEST:PassengerStopAssignment:ssp2:LOC").getQuayRef().getValue().getRef(), "TEST:Quay:quay2");
        Assert.assertNull(result.getStopAssignments().get("TEST:PassengerStopAssignment:ssp3:LOC").getQuayRef());
    }

    @Test
    public void shouldExportAllQuayRefs_WhenComplementaryFileUsed_WithGeneration() throws Exception {
        Context context = createContext(true, true, false, true); // quay2 importé, les autres générés
        context.put(CREATION_DATE, LocalDateTime.now());
        new NetexLineDataFranceProducer().produce(context);
        ExportableNetexData result = (ExportableNetexData) context.get(EXPORTABLE_NETEX_DATA);

        // Tous les QuayRef doivent être présents
        Assert.assertEquals(result.getStopAssignments().get("TEST:PassengerStopAssignment:ssp1:LOC").getQuayRef().getValue().getRef(), "TEST:Quay:quay1");
        Assert.assertEquals(result.getStopAssignments().get("TEST:PassengerStopAssignment:ssp2:LOC").getQuayRef().getValue().getRef(), "TEST:Quay:quay2");
        Assert.assertEquals(result.getStopAssignments().get("TEST:PassengerStopAssignment:ssp3:LOC").getQuayRef().getValue().getRef(), "TEST:Quay:quay3");
	}
}
