ARG CHOUETTE_BASE_VERSION

FROM $CHOUETTE_BASE_VERSION

RUN  yum list installed iproute \
        || sed -i s/mirror.centos.org/vault.centos.org/g /etc/yum.repos.d/*.repo \
        && sed -i s/^#.*baseurl=http/baseurl=http/g /etc/yum.repos.d/*.repo \
        && sed -i s/^mirrorlist=http/#mirrorlist=http/g /etc/yum.repos.d/*.repo \
        && yum makecache \
        && yum -y install iproute \
        && yum install -y https://download.postgresql.org/pub/repos/yum/reporpms/EL-7-x86_64/pgdg-redhat-repo-latest.noarch.rpm && \
          yum install -y https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm && \
          yum install -y libzstd && \
          yum -y install postgresql15

COPY chouette_iev/target/chouette.ear /tmp/chouette.ear

CMD [ "/opt/jboss/wildfly/bin/standalone.sh", "-b", "0.0.0.0", "-bmanagement", "0.0.0.0", "--debug"]
