---
#- set_fact: build_home="/var/lib/jenkins/workspace/chouette"
# - set_fact: build_home="/home/en/git/rutebanken/chouette"
#- set_fact: build_log_directory="/var/lib/jenkins/logs/builds"
- set_fact: logfile="{{build_log_directory}}/chouette.log"

- name: Make log directory structure
  file: path={{build_log_directory}} state=directory mode=0755 group=users

- name: Make chouette target directory structure
  file: path={{chouette_root}}/ state=directory mode=0755 group=users

- name: Upload the wildfly setup directory to the docker host
  synchronize: src=files/wildfly dest={{chouette_root}}/.

- name: Upload disk usage notifier
  copy: src=disk_usage_notifier.sh dest={{chouette_root}}/disk_usage_notifier.sh

- name: Upload jxm exporter config
  copy: src=jmx_exporter_config.yml dest={{chouette_root}}/jmx_exporter_config.yml

- name: Copy the chouette sources to staging directory
  command: rsync -ar {{ build_home }}/chouette_iev/target/chouette.ear {{chouette_root}}/chouette.ear

- name: Move Dockerfile
  template: src=Dockerfile.j2 dest={{chouette_root}}/Dockerfile mode=0755

- name: Copy global libs for wildfly custo
  copy: src=files/{{item.filename}} dest={{chouette_root}}/{{item.filename}}
  with_items:
    - { filename: "hibernate-spatial-4.3.jar" }
    - { filename: "postgis-jdbc-2.1.7.2.jar" }
    - { filename: "jts-1.13.jar" }
    - { filename: "jaxb-impl-2.2.11.jar" }
    - { filename: "jaxb-core-2.2.11.jar" }
    - { filename: "jaxb-xjc-2.2.11.jar" }
    - { filename: "jaxb-xjc-2.2.11.jar" }
    - { filename: "xercesImpl-2.11.0.SP6-RB.jar" }
    - { filename: "postgresql-9.3-1103.jdbc41.jar" }

- name: Build the chouette docker image
  shell: docker build --tag={{ chouette_docker_image|quote }} --force-rm=true {{chouette_root}} > {{logfile}} 2>&1
  register: image

- name: Push chouette docker image if built
  when: image.changed
  shell: docker push {{ chouette_docker_image|quote }} > {{logfile}} 2>&1
