package mobi.chouette.exchange.importer.updater.netex;

import lombok.extern.log4j.Log4j;
import mobi.chouette.model.KeyValue;
import mobi.chouette.model.StopArea;
import mobi.chouette.model.type.ChouetteAreaEnum;
import mobi.chouette.model.type.TransportModeNameEnum;
import mobi.chouette.model.util.Referential;
import org.apache.commons.collections.CollectionUtils;
import org.apache.commons.lang.StringUtils;
import org.rutebanken.netex.model.*;

import java.math.BigDecimal;
import java.util.*;
import java.util.stream.Collectors;

import static mobi.chouette.common.Constant.IMPORTED_ID;
import static mobi.chouette.common.Constant.TTS_NAME_KEY;
import static mobi.chouette.exchange.importer.updater.NeTExStopPlaceRegisterUpdater.*;

/**
 * Map from chouette model to NeTEx
 */
@Log4j
public class StopPlaceMapper {

    private static final String VERSION = "1";

    private static final ObjectFactory netexObjectFactory = new ObjectFactory();

    /**
     * Map stop area with contained stop areas.
     *
     * @param stopArea Typically stop areas of {@link ChouetteAreaEnum#StopPlace} or
     *                 {@link ChouetteAreaEnum#CommercialStopPoint}
     * @return NeTEx stop place
     */
    public StopPlace mapStopAreaToStopPlace(StopArea stopArea) {
        StopPlace stopPlace = mapStopPlace(stopArea);
        if (CollectionUtils.isNotEmpty(stopArea.getContainedStopAreas())) {
            List<String> alreadyProcessedQuays = new ArrayList<>();
            stopPlace.setQuays(new Quays_RelStructure());
            for (StopArea children : stopArea.getContainedStopAreas()) {

                if (alreadyProcessedQuays.contains(children.getObjectId()))
                    continue;

				if (children.getQuayAutoGenerated()) {
                    if (children.getLongitude().equals(new BigDecimal(0))) {
                       children.setLongitude(children.getParent().getLongitude());
                    }
					if (children.getLatitude().equals(new BigDecimal(0))) {
					   children.setLatitude(children.getParent().getLatitude());
					}
                }

                Quay quay = mapQuay(children);

                stopPlace.getQuays().getQuayRefOrQuay().add(netexObjectFactory.createQuay(quay));
                alreadyProcessedQuays.add(children.getObjectId());
            }
        }

        return stopPlace;
    }

    protected Quay mapQuay(StopArea stopArea) {
        Quay quay = new Quay();
        mapId(stopArea, quay);
        setVersion(quay);
        mapCentroid(stopArea, quay);
        mapQuayName(stopArea, quay);
        mapPublicCode(stopArea, quay);
        mapPrivateCode(stopArea, quay);
        mapUrl(stopArea, quay);
        mapCompassBearing(stopArea, quay);
        mapComment(stopArea, quay);
        mapMobilityRestrictedSuitable(stopArea, quay);
        addExternalRefInfo(stopArea, quay);
        addZoneIdInfo(stopArea, quay);
		addIsGeneratedQuayInfo(stopArea, quay);
        setTtsStopNameAsAlternativeName(stopArea, quay);
        return quay;
    }

    private void setTtsStopNameAsAlternativeName(StopArea stopArea, SiteElement_VersionStructure target) {
        Optional<AlternativeName> alternativeName = mapTtsStopName(stopArea);
        if (alternativeName.isPresent()) {
            AlternativeName alternativeNameValue = alternativeName.get();
            if (target.getAlternativeNames() == null) {
                AlternativeNames_RelStructure alternativeNamesRelStructure = new AlternativeNames_RelStructure();
                alternativeNamesRelStructure.getAlternativeName().add(alternativeNameValue);
                target.setAlternativeNames(alternativeNamesRelStructure);
            } else {
                target.getAlternativeNames().getAlternativeName().add(alternativeNameValue);
            }
        }
    }

    public void mapMobilityRestrictedSuitable(StopArea stopArea, Quay quay) {
        AccessibilityAssessment accessibilityAssessment = new AccessibilityAssessment();
        AccessibilityLimitations_RelStructure accessibilityLimitationsRelStructure = new AccessibilityLimitations_RelStructure();
        AccessibilityLimitation accessibilityLimitation = new AccessibilityLimitation();
        if (stopArea.getMobilityRestrictedSuitable() == null) {
            accessibilityLimitation.setWheelchairAccess(LimitationStatusEnumeration.UNKNOWN);
        } else if (!stopArea.getMobilityRestrictedSuitable()) {
            accessibilityLimitation.setWheelchairAccess(LimitationStatusEnumeration.FALSE);
        } else {
            accessibilityLimitation.setWheelchairAccess(LimitationStatusEnumeration.TRUE);
        }
        accessibilityLimitation.setVersion(VERSION);
        accessibilityLimitationsRelStructure.setAccessibilityLimitation(accessibilityLimitation);
        accessibilityAssessment.setLimitations(accessibilityLimitationsRelStructure);
        accessibilityAssessment.setVersion(VERSION);
        quay.setAccessibilityAssessment(accessibilityAssessment);
    }

    public void mapComment(StopArea stopArea, Quay quay) {
        if (StringUtils.isNotBlank(stopArea.getComment())) {
            quay.setDescription(new MultilingualString().withValue(stopArea.getComment()));
        }
    }

    public void mapUrl(StopArea stopArea, Quay quay) {
        if (StringUtils.isNotBlank(stopArea.getUrl())) {
            quay.setUrl(stopArea.getUrl());
        }
    }

    public void mapPublicCode(StopArea stopArea, Quay quay) {
        if (StringUtils.isNotBlank(stopArea.getRegistrationNumber())) {
            quay.setPublicCode(stopArea.getRegistrationNumber());
        }
    }

    private void mapPrivateCode(StopArea stopArea, Quay quay) {
        if (StringUtils.isNotBlank(stopArea.getPrivateCode())) {
            quay.setPrivateCode(new PrivateCodeStructure().withValue(stopArea.getPrivateCode()));
        }
    }

    public void mapPublicCode(StopArea stopArea, StopPlace stopPlace) {
        if (StringUtils.isNotBlank(stopArea.getRegistrationNumber())) {
            stopPlace.setPublicCode(stopArea.getRegistrationNumber());
        }
    }

    private void mapPrivateCode(StopArea stopArea, StopPlace stopPlace) {
        if (StringUtils.isNotBlank(stopArea.getPrivateCode())) {
            stopPlace.setPrivateCode(new PrivateCodeStructure().withValue(stopArea.getPrivateCode()));
        }
    }

    private StopPlace mapStopPlace(StopArea stopArea) {
        StopPlace stopPlace = new StopPlace();
        mapId(stopArea, stopPlace);
        setVersion(stopArea, stopPlace);
        mapCentroid(stopArea, stopPlace);
        mapName(stopArea, stopPlace);
        mapPublicCode(stopArea, stopPlace);
        mapPrivateCode(stopArea, stopPlace);
        addExternalRefInfo(stopArea, stopPlace);
        addZoneIdInfo(stopArea, stopPlace);
        addRailUICinfo(stopArea, stopPlace);
        mapTarifZoneRef(stopArea, stopPlace);
        setTtsStopNameAsAlternativeName(stopArea, stopPlace);
        return stopPlace;
    }

    private Optional<AlternativeName> mapTtsStopName(StopArea stopArea) {
        Optional<AlternativeName> alternativeNameResult = Optional.empty();
        if (StringUtils.isNotBlank(stopArea.getTtsStopName())) {
            AlternativeName alternativeName = new AlternativeName();
            MultilingualString multilingualString = new MultilingualString();
            multilingualString.setValue(stopArea.getTtsStopName());
            alternativeName.setName(multilingualString);
            alternativeName.setTypeOfName(TTS_NAME_KEY);
            alternativeNameResult =  Optional.of(alternativeName);
        }
        return alternativeNameResult;
    }

    private void addRailUICinfo(StopArea stopArea, StopPlace zone) {
        if (StringUtils.isNotBlank(stopArea.getRailUic())) {
            zone.withKeyList(new KeyListStructure().withKeyValue(new KeyValueStructure()
                    .withKey(RAIL_UIC)
                    .withValue(stopArea.getRailUic())));
        }
    }

    private void mapTarifZoneRef(StopArea stopArea, StopPlace stopPlace) {
        if (StringUtils.isNotBlank(stopArea.getZoneId())) {
            stopPlace.setTariffZones(new TariffZoneRefs_RelStructure());
            ZoneRefStructure tariffZone = new ZoneRefStructure();
            tariffZone.setRef(stopArea.getZoneId());
            stopPlace.getTariffZones().getTariffZoneRef_().add(netexObjectFactory.createTariffZoneRef_(tariffZone));
        }
    }

    private void mapCompassBearing(StopArea stopArea, Quay quay) {
        if (stopArea.getCompassBearing() != null) {
            quay.setCompassBearing(Float.valueOf(stopArea.getCompassBearing()));
        }
    }

    public void setVersion(StopArea stopArea, EntityInVersionStructure entity) {
        entity.setVersion(String.valueOf(stopArea.getObjectVersion()));
    }

    public void setVersion(EntityInVersionStructure entity) {
        entity.setVersion(VERSION);
    }

    private void mapId(StopArea stopArea, Zone_VersionStructure zone) {
        zone.setId(stopArea.getObjectId());
    }

    public void replaceIdIfQuayOrStopPlace(Zone_VersionStructure zone) {
        zone.setId(zone.getId());
    }

    private void mapCentroid(StopArea stopArea, Zone_VersionStructure zone) {
        setVersion(stopArea, zone);
        if (stopArea.getLatitude() != null && stopArea.getLongitude() != null) {
            zone.setCentroid(new SimplePoint_VersionStructure().withLocation(
                    new LocationStructure().withLatitude(stopArea.getLatitude()).withLongitude(stopArea.getLongitude())));
        }
    }

    private void mapName(StopArea stopArea, Zone_VersionStructure zone) {
        zone.setName(new MultilingualString().withValue(stopArea.getName()).withLang("fr").withTextIdType(""));
    }

    private void mapQuayName(StopArea stopArea, Zone_VersionStructure zone) {
        if (StringUtils.isNotBlank(stopArea.getName())) {
            zone.setName(new MultilingualString().withValue(stopArea.getName()).withLang("fr").withTextIdType(""));
        }
    }

    public void mapTransportMode(StopPlace sp, TransportModeNameEnum mode) {
        switch (mode) {
            case Air:
                sp.setStopPlaceType(StopTypeEnumeration.AIRPORT);
                break;
            case Bus:
            case Coach:
                sp.setStopPlaceType(StopTypeEnumeration.ONSTREET_BUS);
                break;
            case Water:
            case Ferry:
                sp.setStopPlaceType(StopTypeEnumeration.FERRY_STOP);
                break;
            case Metro:
                sp.setStopPlaceType(StopTypeEnumeration.METRO_STATION);
                break;
            case Funicular:
                sp.setTransportMode(AllVehicleModesOfTransportEnumeration.FUNICULAR);
                sp.setStopPlaceType(StopTypeEnumeration.METRO_STATION);
                break;
            case Rail:
                sp.setStopPlaceType(StopTypeEnumeration.RAIL_STATION);
                break;
            case TrolleyBus:
            case Tram:
                sp.setStopPlaceType(StopTypeEnumeration.ONSTREET_TRAM);
                break;
            default:
                log.warn("Could not map stop place type for stop place " + sp.getId() + " Chouette type was: " + mode + ". Mapping to type OTHER");
                sp.setStopPlaceType(StopTypeEnumeration.OTHER);
        }
        log.debug("Mapped stop place type from " + mode + " to " + sp.getStopPlaceType() + " for stop " + sp.getId());
    }

    /**
     * Add imported id if found in referential
     *
     * @param stopPlace   Netex stop place
     * @param referential chouette import referential
     * @return Netex stop place augmented with imported id if found.
     */
    public StopPlace addImportedIdInfo(StopPlace stopPlace, Referential referential) {
        Map<String, String> stopAreaMappingInverse = new HashMap<>();
        for (Map.Entry<String, String> entry : referential.getStopAreaMapping().entrySet()) {
            stopAreaMappingInverse.put(entry.getValue(), entry.getKey());
        }
        String importedId = stopAreaMappingInverse.get(stopPlace.getId());
        if (StringUtils.isNotBlank(importedId)) {
            stopPlace.withKeyList(new KeyListStructure().withKeyValue(new KeyValueStructure()
                    .withKey(IMPORTED_ID)
                    .withValue(importedId)));
        }
        return stopPlace;
    }

    public void addExternalRefInfo(StopArea stopArea, Zone_VersionStructure zone) {
        for (KeyValue keyValue : stopArea.getKeyValues()) {
            if(StringUtils.equals(keyValue.getKey(), EXTERNAL_REF) && StringUtils.isNotEmpty(keyValue.getValue())){
                zone.setKeyList(new KeyListStructure().withKeyValue(new KeyValueStructure()
                        .withKey(EXTERNAL_REF)
                        .withValue(keyValue.getValue())));
            }
        }
    }

	public void addIsGeneratedQuayInfo(StopArea stopArea, Zone_VersionStructure zone) {
		for (KeyValue keyValue : stopArea.getKeyValues()) {
			if(StringUtils.equals(keyValue.getKey(), AUTO_CREATED_QUAY_SUFFIX) && StringUtils.isNotEmpty(keyValue.getValue())){
				zone.setKeyList(new KeyListStructure().withKeyValue(new KeyValueStructure()
						.withKey(AUTO_CREATED_QUAY_SUFFIX)
						.withValue(keyValue.getValue())));
			}
		}
	}

    public void addZoneIdInfo(StopArea stopArea, Zone_VersionStructure zone) {
        if (StringUtils.isNotBlank(stopArea.getZoneId())) {
            zone.withKeyList(new KeyListStructure().withKeyValue(new KeyValueStructure()
                    .withKey(FARE_ZONE)
                    .withValue(stopArea.getZoneId())));
        }
    }
}
